# Generated by Django 4.1.7 on 2023-06-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=10)),
                ('diagnosis_code', models.CharField(max_length=10)),
                ('full_code', models.CharField(max_length=10)),
                ('abbreviated_description', models.CharField(max_length=255)),
                ('full_description', models.CharField(max_length=255)),
                ('category_title', models.CharField(max_length=255)),
                ('icd_version', models.CharField(default='ICD-10', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diagnosis Code',
                'verbose_name_plural': 'Diagnosis Codes',
            },
        ),
    ]
